application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 300000 # a day (1000*60 -> 1 min *5 -> 5 min)
      refresh-token:
        expiration: 604800000 # 7 days



spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ss_example8
    username: root
    password: root1234
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect

